name: Validate for PR
on: push
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: make deps ci-test lint build acceptance-test
        env:
          GO111MODULE: on
