name: Release workflow
on:
  push:
    tags:
      - 'v*'
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        env:
          GO111MODULE: on
        with:
          go-version: '1.13'
      - run: make test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ validate ]
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install Deps
      run: make build-deps
      env:
        GO111MODULE: on
    - name: Perform release
      run: ./bin/goreleaser release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GO111MODULE: on
      if: success()
